---
- name: add mongo repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
    state: present
  tags: install

- name: add mongo repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: install mongo database
  apt: name=mongodb-org state=present
  tags: install

- name: enable mongo unit
  service: name=mongod enabled=yes
  tags: install
